package com.portfolio.config;

import com.portfolio.model.Country;
import com.portfolio.repository.CountryRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Seeds the countries table on first run with all ISO 3166-1 countries.
 */
@Component
@Order(1)
public class CountrySeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(CountrySeeder.class);
    private final CountryRepository repo;

    public CountrySeeder(CountryRepository repo) {
        this.repo = repo;
    }

    @Override
    public void run(ApplicationArguments args) {
        if (repo.count() > 0) return; // already seeded

        List<Country> countries = List.of(
            new Country("AF", "Afghanistan"),
            new Country("AL", "Albania"),
            new Country("DZ", "Algeria"),
            new Country("AD", "Andorra"),
            new Country("AO", "Angola"),
            new Country("AG", "Antigua and Barbuda"),
            new Country("AR", "Argentina"),
            new Country("AM", "Armenia"),
            new Country("AU", "Australia"),
            new Country("AT", "Austria"),
            new Country("AZ", "Azerbaijan"),
            new Country("BS", "Bahamas"),
            new Country("BH", "Bahrain"),
            new Country("BD", "Bangladesh"),
            new Country("BB", "Barbados"),
            new Country("BY", "Belarus"),
            new Country("BE", "Belgium"),
            new Country("BZ", "Belize"),
            new Country("BJ", "Benin"),
            new Country("BT", "Bhutan"),
            new Country("BO", "Bolivia"),
            new Country("BA", "Bosnia and Herzegovina"),
            new Country("BW", "Botswana"),
            new Country("BR", "Brazil"),
            new Country("BN", "Brunei"),
            new Country("BG", "Bulgaria"),
            new Country("BF", "Burkina Faso"),
            new Country("BI", "Burundi"),
            new Country("CV", "Cabo Verde"),
            new Country("KH", "Cambodia"),
            new Country("CM", "Cameroon"),
            new Country("CA", "Canada"),
            new Country("CF", "Central African Republic"),
            new Country("TD", "Chad"),
            new Country("CL", "Chile"),
            new Country("CN", "China"),
            new Country("CO", "Colombia"),
            new Country("KM", "Comoros"),
            new Country("CG", "Congo"),
            new Country("CD", "Congo (DRC)"),
            new Country("CR", "Costa Rica"),
            new Country("CI", "Côte d'Ivoire"),
            new Country("HR", "Croatia"),
            new Country("CU", "Cuba"),
            new Country("CY", "Cyprus"),
            new Country("CZ", "Czech Republic"),
            new Country("DK", "Denmark"),
            new Country("DJ", "Djibouti"),
            new Country("DM", "Dominica"),
            new Country("DO", "Dominican Republic"),
            new Country("EC", "Ecuador"),
            new Country("EG", "Egypt"),
            new Country("SV", "El Salvador"),
            new Country("GQ", "Equatorial Guinea"),
            new Country("ER", "Eritrea"),
            new Country("EE", "Estonia"),
            new Country("SZ", "Eswatini"),
            new Country("ET", "Ethiopia"),
            new Country("FJ", "Fiji"),
            new Country("FI", "Finland"),
            new Country("FR", "France"),
            new Country("GA", "Gabon"),
            new Country("GM", "Gambia"),
            new Country("GE", "Georgia"),
            new Country("DE", "Germany"),
            new Country("GH", "Ghana"),
            new Country("GR", "Greece"),
            new Country("GD", "Grenada"),
            new Country("GT", "Guatemala"),
            new Country("GN", "Guinea"),
            new Country("GW", "Guinea-Bissau"),
            new Country("GY", "Guyana"),
            new Country("HT", "Haiti"),
            new Country("HN", "Honduras"),
            new Country("HU", "Hungary"),
            new Country("IS", "Iceland"),
            new Country("IN", "India"),
            new Country("ID", "Indonesia"),
            new Country("IR", "Iran"),
            new Country("IQ", "Iraq"),
            new Country("IE", "Ireland"),
            new Country("IL", "Israel"),
            new Country("IT", "Italy"),
            new Country("JM", "Jamaica"),
            new Country("JP", "Japan"),
            new Country("JO", "Jordan"),
            new Country("KZ", "Kazakhstan"),
            new Country("KE", "Kenya"),
            new Country("KI", "Kiribati"),
            new Country("KP", "Korea (North)"),
            new Country("KR", "Korea (South)"),
            new Country("KW", "Kuwait"),
            new Country("KG", "Kyrgyzstan"),
            new Country("LA", "Laos"),
            new Country("LV", "Latvia"),
            new Country("LB", "Lebanon"),
            new Country("LS", "Lesotho"),
            new Country("LR", "Liberia"),
            new Country("LY", "Libya"),
            new Country("LI", "Liechtenstein"),
            new Country("LT", "Lithuania"),
            new Country("LU", "Luxembourg"),
            new Country("MG", "Madagascar"),
            new Country("MW", "Malawi"),
            new Country("MY", "Malaysia"),
            new Country("MV", "Maldives"),
            new Country("ML", "Mali"),
            new Country("MT", "Malta"),
            new Country("MH", "Marshall Islands"),
            new Country("MR", "Mauritania"),
            new Country("MU", "Mauritius"),
            new Country("MX", "Mexico"),
            new Country("FM", "Micronesia"),
            new Country("MD", "Moldova"),
            new Country("MC", "Monaco"),
            new Country("MN", "Mongolia"),
            new Country("ME", "Montenegro"),
            new Country("MA", "Morocco"),
            new Country("MZ", "Mozambique"),
            new Country("MM", "Myanmar"),
            new Country("NA", "Namibia"),
            new Country("NR", "Nauru"),
            new Country("NP", "Nepal"),
            new Country("NL", "Netherlands"),
            new Country("NZ", "New Zealand"),
            new Country("NI", "Nicaragua"),
            new Country("NE", "Niger"),
            new Country("NG", "Nigeria"),
            new Country("MK", "North Macedonia"),
            new Country("NO", "Norway"),
            new Country("OM", "Oman"),
            new Country("PK", "Pakistan"),
            new Country("PW", "Palau"),
            new Country("PS", "Palestine"),
            new Country("PA", "Panama"),
            new Country("PG", "Papua New Guinea"),
            new Country("PY", "Paraguay"),
            new Country("PE", "Peru"),
            new Country("PH", "Philippines"),
            new Country("PL", "Poland"),
            new Country("PT", "Portugal"),
            new Country("QA", "Qatar"),
            new Country("RO", "Romania"),
            new Country("RU", "Russia"),
            new Country("RW", "Rwanda"),
            new Country("KN", "Saint Kitts and Nevis"),
            new Country("LC", "Saint Lucia"),
            new Country("VC", "Saint Vincent and the Grenadines"),
            new Country("WS", "Samoa"),
            new Country("SM", "San Marino"),
            new Country("ST", "São Tomé and Príncipe"),
            new Country("SA", "Saudi Arabia"),
            new Country("SN", "Senegal"),
            new Country("RS", "Serbia"),
            new Country("SC", "Seychelles"),
            new Country("SL", "Sierra Leone"),
            new Country("SG", "Singapore"),
            new Country("SK", "Slovakia"),
            new Country("SI", "Slovenia"),
            new Country("SB", "Solomon Islands"),
            new Country("SO", "Somalia"),
            new Country("ZA", "South Africa"),
            new Country("SS", "South Sudan"),
            new Country("ES", "Spain"),
            new Country("LK", "Sri Lanka"),
            new Country("SD", "Sudan"),
            new Country("SR", "Suriname"),
            new Country("SE", "Sweden"),
            new Country("CH", "Switzerland"),
            new Country("SY", "Syria"),
            new Country("TW", "Taiwan"),
            new Country("TJ", "Tajikistan"),
            new Country("TZ", "Tanzania"),
            new Country("TH", "Thailand"),
            new Country("TL", "Timor-Leste"),
            new Country("TG", "Togo"),
            new Country("TO", "Tonga"),
            new Country("TT", "Trinidad and Tobago"),
            new Country("TN", "Tunisia"),
            new Country("TR", "Turkey"),
            new Country("TM", "Turkmenistan"),
            new Country("TV", "Tuvalu"),
            new Country("UG", "Uganda"),
            new Country("UA", "Ukraine"),
            new Country("AE", "United Arab Emirates"),
            new Country("GB", "United Kingdom"),
            new Country("US", "United States"),
            new Country("UY", "Uruguay"),
            new Country("UZ", "Uzbekistan"),
            new Country("VU", "Vanuatu"),
            new Country("VA", "Vatican City"),
            new Country("VE", "Venezuela"),
            new Country("VN", "Vietnam"),
            new Country("YE", "Yemen"),
            new Country("ZM", "Zambia"),
            new Country("ZW", "Zimbabwe")
        );

        repo.saveAll(countries);
        log.info("Seeded {} countries", countries.size());
    }
}
