package com.portfolio.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * One-time fix: drops stale CHECK constraints on the asset_type column
 * that were generated by Hibernate before new enum values (e.g. CASH) were added.
 * Hibernate's ddl-auto=update does not update existing check constraints.
 */
@Component
@Order(1)
public class SchemaFixMigration implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(SchemaFixMigration.class);

    private final JdbcTemplate jdbc;

    public SchemaFixMigration(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public void run(ApplicationArguments args) {
        try {
            List<String> constraints = jdbc.queryForList(
                    "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS " +
                    "WHERE TABLE_NAME = 'INVESTMENTS' AND CONSTRAINT_TYPE = 'CHECK'",
                    String.class
            );
            for (String name : constraints) {
                log.info("Dropping stale CHECK constraint: {}", name);
                jdbc.execute("ALTER TABLE investments DROP CONSTRAINT IF EXISTS " + name);
            }
        } catch (Exception e) {
            log.debug("Schema fix skipped (may not be H2): {}", e.getMessage());
        }
    }
}
